services:
  frontend:
    container_name: finance-analyser-frontend
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:80"
    environment:
      - PORT=80
      - API_BASE_URL=http://localhost:3000/api
    volumes:
      - .:/app