services:
  frontend:
    container_name: finance-analyser-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - API_BASE_URL=http://localhost:3000/api
    volumes:
      - .:/app