services:
  frontend:
    extends:
      file: frontend/docker-compose.yaml
      service: frontend
    environment:
      - PORT=80
      - API_BASE_URL=http://localhost:3000/api
    ports:
      - "80:80"
  backend:
    extends:
      file: backend/docker-compose.yaml
      service: fin-analy-express
    environment:
      - PORT=3000
  mongo:
    extends:
      file: backend/docker-compose.yaml
      service: mongo

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - fin-analy-network
      
networks:
  fin-analy-network:
    driver: bridge

volumes:
  mongo_data: