services:
  fin-analy-express:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/fin-analy-db
      - PORT=3000
      - API_PREFIX=/api
    networks:
      - fin-analy-network

  mongo:
    image: mongo:latest
    # ports:
    #   - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - fin-analy-network

networks:
  fin-analy-network:
    driver: bridge
    
volumes:
  mongo_data: