# @name login
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "testuser1@email.com",
  "password": "testpassword"
}

###
@authToken = {{login.response.headers.X-AuthToken}}
###

### GET transactions
GET http://localhost:3000/api/transactions
Content-Type: application/json
Authorization: Bearer {{authToken}}

### POST create
### create expense 1
POST http://localhost:3000/api/transactions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "amount": 170.5,
  "category": "Groceries",
  "description": "Weekly grocery shopping",
  "type": "expense"
}

### create expense 2
POST http://localhost:3000/api/transactions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "amount": 169.11,
  "category": "Toy Store",
  "description": "Kids' birthday gift",
  "type": "expense"
}

### create income
POST http://localhost:3000/api/transactions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "amount": 1000,
  "category": "Salary",
  "description": "Monthly salary payment",
  "type": "income"
}

### create income 2
POST http://localhost:3000/api/transactions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "amount": 1000,
  "category": "tmp1",
  "description": "Monthly salary payment",
  "type": "income"
}



### GET all transactions
# @name getAllTransactions
GET http://localhost:3000/api/transactions
Content-Type: application/json
Authorization:  Bearer {{authToken}}

### 
@transactionId1 = {{getAllTransactions.response.body.0.id}}

### DELETE transaction
### delete expense 1
DELETE http://localhost:3000/api/transactions/{{transactionId1}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

